#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias fix-spotlight="find . -type d -path './.*' -prune -o -path './Pictures*' -prune -o -path './Library*' -prune -o -path '*node_modules/*' -prune -o -type d -name 'node_modules' -exec touch '{}/.metadata_never_index' \; -print"

# finds the process using a particular port and kills it
killport() {  local PORT=$(lsof -n -i4TCP:$1 | grep LISTEN | awk '{ print $2 }'); kill -9 $PORT }

alias rr="source ~/.zshrc; clear"

# for remote ssh code
# alias code="${VSCODE_GIT_ASKPASS_NODE%/*}/bin/code"
export PATH=${VSCODE_GIT_ASKPASS_NODE%/*}/bin/remote-cli:$PATH
# export PATH=/Users/rai/bin:$PATH

# START CURSOR TERMINAL FIX
# formats cursor in terminal
function zle-keymap-select () {
  case $KEYMAP in
    vicmd) echo -ne '\e[1 q';; # block
    viins|main) echo -ne '\e[5 q';; # beam
  esac
}

zle -N zle-keymap-select

zle-line-init() {
  zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
  echo -ne "\e[5 q"
}

zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.


# END CURSOR TERMINAL FIX 

path+=('/users/rai/bin')
export PATH
rcode() {
  target_path=$1
  code --folder-uri=scode-remote://ssh-remote+192.168.50.200/Users/rai/$target_path
}

alias code="code-insiders"

# for rdcli
export REALDEBRID_USERNAME=rai@rbutera.com

# to enable ctrl+R in vi mode
bindkey "^R" history-incremental-search-backward

# starship prompt (should be last)
eval "$(starship init zsh)"

