#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias fix-spotlight="find . -type d -path './.*' -prune -o -path './Pictures*' -prune -o -path './Library*' -prune -o -path '*node_modules/*' -prune -o -type d -name 'node_modules' -exec touch '{}/.metadata_never_index' \; -print"

# finds the process using a particular port and kills it
killport() {  local PORT=$(lsof -n -i4TCP:$1 | grep LISTEN | awk '{ print $2 }'); kill -9 $PORT }

alias rr="source ~/.zshrc; clear"

# for remote ssh code
# alias code="${VSCODE_GIT_ASKPASS_NODE%/*}/bin/code"
# export PATH=${VSCODE_GIT_ASKPASS_NODE%/*}/bin:$PATH
# export PATH=/Users/rai/bin:$PATH

# starship prompt (should be last)
eval "$(starship init zsh)"

